### PR TITLE
Fix to escape backslashes in the original html/css templates before they are put into string/template literals in the final output

### LINKED ISSUE #50: Remove baskslash in pattern attribute
Hi,

It seems that the plugin remove backslash in pattern attributes when inlining the template.

Before :

``` html
<input type="text" [(ngModel)]="search.imei" id="form-imei" class="form-control" pattern="\d+" required />
```

After : 

``` html
<input type="text" [(ngModel)]="search.imei" id="form-imei" class="form-control" pattern="d+" required />
```

Thanks in advance

### PR DESCRIPTION
**Pull request by gregjacobs**
Fixes #50

### CODE REVIEW

File: test/fixtures/result_expected.js [hunk 1]
```diff
@@ -15,7 +15,7 @@
       color: red;
     }
     smile:before {
-      content: "\000B";
+      content: "\\000B";
```
Comment (gregjacobs) [inline test/fixtures/result_expected.js]: These all needed their backslashes escaped so they will be created in memory as the string `\000B` rather than `[null character]B`

Comment (gregjacobs) [inline test/fixtures/result_expected.js]: Actually, because `\000B` appears inside a template literal in this file, the JS engine would simply throw an error for not allowing the deprecated octal literals.

It's accepted in non-strict mode ES5 though as `[null character]B`

**Comment by ludohenin** [comment]
Awesome, thanks for the PRs, will check and merge that during the week-end.

**Comment by gregjacobs** [comment]
Hey, np man. 

Just one thought: might want to release this change as 4.0, in case anyone had their own workarounds for backslashes in either `templateProcessor` or `styleProcessor`. Could put in the release notes that those workarounds can now be removed.

**Comment by ludohenin** [comment]
Release as `v4.0.0`

**Comment by gregjacobs** [comment]
Awesome, this should help a lot of people out. Thanks for merging, and your work on this project!
